---
title: "The Alchemy of Academics: Investigating the forces influencing academic performance in Singapore"
subtitle: "How do psychological, socioeconomic, and environmental factors affect the outcomes of Singapore’s meritocratic education system? Our team sets out to find answers."
title-block-banner: true
toc: true
editor: visual
execute: 
  freeze: auto
  warning: false
  #echo: false
  #message: false
  html:
    code-fold: True
    code-overflow: scroll
    code-summary: "Show the code"
    code-line-numbers: true
---

# Overview & Motivation

Singapore has come a long way since gaining independence in 1965. Without natural resources, human capital development through a well-planned, world-class education system was a critical part of Singapore's transformation from third world to first. Despite the internationally lauded success, Singapore's education system is far from perfect -- there still exists gaps in education achievement among students. According to the latest OECD's Programme for International Student Assessment (PISA) 2022, which measures 15-year-olds' ability to use their reading, mathematics, and science knowledge and skills to meet real-life challenges, socio-economic status accounted for 17% of the variation in mathematics performance in Singapore (compared to 15% on average across OECD countries). Clearly, Singapore's success does not translate to success for every student. Why then do some students outperform others?

Our team believes that knowledge is power. While causality cannot and should not be easily drawn between the various forces of influence and academic performance, a more detailed and nuanced understanding of these factors would highlight potential areas to focus on when engaging parents and students as well as developing education and socioeconomic policies for a more inclusive and equitable society.

# Problem Statement

The PISA is treated as a platform for geopolitical competition, as shown by an overemphasis on the comparison of PISA scores between different countries. Scant attention is paid to the extensive data collected through the student, parent, and school questionnaires that are administered alongside the tests, which may reveal more a nuanced understanding of the individual lived experiences of students.

Research studies on the gaps in education attainment in Singapore tends to focus on traditional factors such as gender, race, and socioeconomic status. While these are important structural factors, they should be complemented by individual-level factors, such as psychological wellness, and social relations. Gen Alpha children are said to have reduced attention span, and less time for socialising. These could pose challenges in their education journeys, and deserve closer attention.

Technical knowledge is required to perform accurate and reliable data wrangling and analysis of the survey outcomes from PISA. Such valuable information should be made available to the public in an accessible and interactive manner for self-discovery.

# Methodology

The team will extract, analyse, and visualise the relationships between different factors and the PISA scores of Singapore students. Using various R packages, an interactive R shiny application with visual analytics techniques will be presented to enable the public to interact with the data based on their personal interests and circumstances, and draw their own insights and conclusions regarding the state of learning in Singapore.

Users will be able to:

-   Compare the PISA scores between different groups of students based on factors such as gender, socioeconomic status (e.g., employment status of parents, immigrant status), and psychological wellbeing (e.g., feeling of loneliness, resilience when faced with challenges).

-   Conduct longitudinal comparisons of PISA scores across different years.

-   Gain an understanding of the varying levels of importance and statistical significance of the various influences on PISA scores for different clusters of students.

Overall, the research hopes to generate new knowledge on disparities in the daily stress experience and psychological well-being between lower and higher SES students, and their spillover effects on academic performance and persistence. The broader implication of the study is that educational policies must actively address psychological challenges along with resource challenges to better mitigate socioeconomic gaps in higher educational attainment.

# The Data

The PISA measures how well 15-year-old students in different countries perform in the subjects of reading, mathematics, and science. The PISA surveys take place every three years -- the latest one was conducted in 2022, after the COVID-19 pandemic. The PISA 2022 database contains the full set of responses from individual students, school principals, teachers, and parents. This project focuses on the student questionnaire data file, retrieved from the [PISA Database](https://www.oecd.org/pisa/data/2022database/).

# Methodology and Analytical Approach

The project will use a combination of Exploratory Data Analysis (EDA) and Confirmatory Data Analysis (CDA) to assess the relationships between academic outcomes and the myriad of factors.

## Exploratory Data Analysis (EDA) via Data Visualisation

For this project, EDA in the form of visualisation techniques will be applied to give the public the ability to obtain evidence-based insights through visual analytics. The availability of a range of psychological, socioeconomic and environmental factors to choose from under the broad categories of individual, family, and school factors provides a multi-faceted view of academic performance.

## Confirmatory Data Analysis (CDA) via Hypothesis Testing and Model Building

For this project, CDA will be two-pronged. One, users can conduct hypothesis testing for the various factors to determine their statistical significance vis-à-vis the PISA scores. Two, users can build a model based on multiple linear regression (and aided by multicollinearity checks) to obtain an integrated perspective of the interplay between different factors on the PISA scores.

# Data Visualisation Methods

-   Raincloud plots to visualise distribution of individual subject scores (target variables)

-   Ternary plot to visualise the performance across 3 different subjects and the possible interplay with each other • Bar charts with error bars

-   Diverging stacked bar chart for likert data

-   Parallel coordinates plot to compare relationship between variables

-   Correlation matrix

-   Streamgraph to analyse performance across time, where the width explains the longevity of explanatory variable and height provides the magnitude of impact to scores.

# R Shiny Packages

| Package                                                     | Description                                                   |
|-------------|-----------------------------------------------------------|
| [tidyverse](https://www.tidyverse.org/)                     |                                                               |
| [DT](https://rstudio.github.io/DT/)                         | For interactive data tables                                   |
| [ggstatplot](https://indrajeetpatil.github.io/ggstatsplot/) | To visual correlation matrix and plots with statistical tests |
| [plotly](https://plotly.com/r/)                             | For interactive, publication-quality plots                    |
|                                                             |                                                               |
|                                                             |                                                               |
|                                                             |                                                               |
|                                                             |                                                               |
|                                                             |                                                               |

# Project Management
