---
title: "Phase 1: Variables"
title-block-banner: true
toc: true
editor: visual
execute: 
  freeze: true
  warning: false
  #echo: false
  #message: false
  html:
    code-fold: True
    code-overflow: scroll
    code-summary: "Show the code"
    code-line-numbers: true
---

+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
|    | **Category**  | **Name**                           | **Description**                                                                                                                                                                            | **Label**                                               |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 1  | Environmental | ST034Q06TA                         | I feel lonely at school.                                                                                                                                                                   | 1 - Strongly agree\                                     |
|    |               |                                    |                                                                                                                                                                                            | 2 - Agree\                                              |
|    |               |                                    |                                                                                                                                                                                            | 3 - Disagree\                                           |
|    |               |                                    |                                                                                                                                                                                            | 4 - Strongly disagree                                   |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 2  | Environmental | ST038Q08NA                         | Other students spread nasty rumours about me.                                                                                                                                              | 1 - Never or almost never\                              |
|    |               |                                    |                                                                                                                                                                                            | 2 - A few times a year\                                 |
|    |               |                                    |                                                                                                                                                                                            | 3 - A few times a month\                                |
|    |               |                                    |                                                                                                                                                                                            | 4 - Once a week or more                                 |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 3  | Environmental | ST038Q09JA                         | In past 12 months, how often: I was in a physical fight on school property.                                                                                                                | 1 - Never or almost never\                              |
|    |               |                                    |                                                                                                                                                                                            | 2 - A few times a year\                                 |
|    |               |                                    |                                                                                                                                                                                            | 3 - A few times a month\                                |
|    |               |                                    |                                                                                                                                                                                            | 4 - Once a week or more                                 |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 4  | Environmental | ST265Q03JA                         | Agree/disagree: I feel safe in my classrooms at school.                                                                                                                                    | 1 - Strongly agree\                                     |
|    |               |                                    |                                                                                                                                                                                            | 2 - Agree\                                              |
|    |               |                                    |                                                                                                                                                                                            | 3 - Disagree\                                           |
|    |               |                                    |                                                                                                                                                                                            | 4 - Strongly disagree                                   |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 5  | Environmental | ST267Q01JA                         | Agree/disagree: The teachers at my school are respectful towards me.                                                                                                                       | 1 - Strongly Disagree\                                  |
|    |               |                                    |                                                                                                                                                                                            | 2 - Disagree\                                           |
|    |               |                                    |                                                                                                                                                                                            | 3 - Agree\                                              |
|    |               |                                    |                                                                                                                                                                                            | 4 - Strongly Agree                                      |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 6  | Environmental | ST267Q07JA                         | Agree/disagree: The teachers at my school are interested in students' well-being.                                                                                                          | 1 - Strongly Disagree\                                  |
|    |               |                                    |                                                                                                                                                                                            | 2 - Disagree\                                           |
|    |               |                                    |                                                                                                                                                                                            | 3 - Agree\                                              |
|    |               |                                    |                                                                                                                                                                                            | 4 - Strongly Agree                                      |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 7  | Gender        | ST004D01T                          | Student (Standardized) Gender                                                                                                                                                              | 1 -- Female; 2 -- Male                                  |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 8  | School        | ST127Q03TA                         | Have you ever repeated a \[grade\]: At \[ISCED 3\]                                                                                                                                         | 1 - No, never\                                          |
|    |               |                                    |                                                                                                                                                                                            | 2 - Yes, once\                                          |
|    |               |                                    |                                                                                                                                                                                            | 3 - Yes, twice or more                                  |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 9  | School        | ST296Q01JA, ST296Q02JA, ST296Q03JA | How much time spent on homework in: \[Subject\] homework                                                                                                                                   | 1 - Up to 30 minutes a day,\                            |
|    |               |                                    |                                                                                                                                                                                            | 2 - More than 30 minutes and up to 1 hour a day,\       |
|    |               |                                    |                                                                                                                                                                                            | 3 - More than 1 hour and up to 2 hours a day,\          |
|    |               |                                    |                                                                                                                                                                                            | 4 - More than 2 hours and up to 3 hours a day,\         |
|    |               |                                    |                                                                                                                                                                                            | 5 - More than 3 hours and up to 4 hours a day,\         |
|    |               |                                    |                                                                                                                                                                                            | 6 - More than 4 hours a day                             |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 10 | School        | STRATUM                            | Stratum ID 5-character (cnt + original stratum ID)                                                                                                                                         | SGP01 - Public / Secondary; SGP03 - Private / Secondary |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 11 | Socioeconomic | HISCED                             | Highest level of education of parents (ISCED)                                                                                                                                              | 1 - Less than ISCED Level 1\                            |
|    |               |                                    |                                                                                                                                                                                            | 2 - ISCED level 1\                                      |
|    |               |                                    |                                                                                                                                                                                            | 3 - ISCED level 2\                                      |
|    |               |                                    |                                                                                                                                                                                            | 4 - ISCED level 3.3\                                    |
|    |               |                                    |                                                                                                                                                                                            | 5 - ISCED level 3.4\                                    |
|    |               |                                    |                                                                                                                                                                                            | 6 - ISCED level 4\                                      |
|    |               |                                    |                                                                                                                                                                                            | 7 - ISCED level 5\                                      |
|    |               |                                    |                                                                                                                                                                                            | 8 - ISCED level 6\                                      |
|    |               |                                    |                                                                                                                                                                                            | 9 - ISCED level 7\                                      |
|    |               |                                    |                                                                                                                                                                                            | 10 - ISCED level 8                                      |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 12 | Socioeconomic | IMMIG                              | Index on immigrant background (OECD definition)                                                                                                                                            | 1 -- Native Student\                                    |
|    |               |                                    |                                                                                                                                                                                            | 2 -- 2nd Generation student\                            |
|    |               |                                    |                                                                                                                                                                                            | 3 -- 1st Generation student                             |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 13 | Socioeconomic | OCOD1                              | ISCO-08 Occupation code - Mother                                                                                                                                                           |                                                         |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 14 | Socioeconomic | OCOD2                              | ISCO-08 Occupation code - Father                                                                                                                                                           |                                                         |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 15 | Socioeconomic | ST019AQ01T                         | In what country were you and your parents born? You                                                                                                                                        | 1 - Country of test\                                    |
|    |               |                                    |                                                                                                                                                                                            | 2 - Other country\                                      |
|    |               |                                    |                                                                                                                                                                                            | 3 -  I don't know.                                      |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 16 | Socioeconomic | ST019BQ01T                         | In what country were you and your parents born? Mother                                                                                                                                     | 1 - Country of test\                                    |
|    |               |                                    |                                                                                                                                                                                            | 2 - Other country\                                      |
|    |               |                                    |                                                                                                                                                                                            | 3 - I don't know.                                       |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 17 | Socioeconomic | ST019CQ01T                         | In what country were you and your parents born? Father                                                                                                                                     | 1 - Country of test\                                    |
|    |               |                                    |                                                                                                                                                                                            | 2 - Other country\                                      |
|    |               |                                    |                                                                                                                                                                                            | 3 - I don't know.                                       |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 18 | Socioeconomic | ST022Q01TA                         | What language do you speak at home most of the time?                                                                                                                                       | 1 - Language of test\                                   |
|    |               |                                    |                                                                                                                                                                                            | 2 - Other country\                                      |
|    |               |                                    |                                                                                                                                                                                            | 3 - I don't know.                                       |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 19 | Socioeconomic | ST230Q01JA                         | How many siblings (including brothers, sisters, step-brothers, and step-sisters) do you have?                                                                                              | 1 - None\                                               |
|    |               |                                    |                                                                                                                                                                                            | 2 - One \                                               |
|    |               |                                    |                                                                                                                                                                                            | 3 - Two \                                               |
|    |               |                                    |                                                                                                                                                                                            | 4 - Three or more                                       |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 20 | Socioeconomic | ST250D06JA                         | Which of the following are in your home? \<Air-conditioner\>                                                                                                                               | 7020001 - Yes\                                          |
|    |               |                                    |                                                                                                                                                                                            | 7020002 - No                                            |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 21 | Socioeconomic | ST250D07JA                         | Which of the following are in your home? \<Domestic helper (e.g. full/part-time maid)\>                                                                                                    | 7020001 - Yes\                                          |
|    |               |                                    |                                                                                                                                                                                            | 7020002 - No                                            |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 22 | Socioeconomic | ST251Q01JA                         | How many of these items are there at your home? Cars, vans, or trucks                                                                                                                      | 1 -- None\                                              |
|    |               |                                    |                                                                                                                                                                                            | 2 -- One \                                              |
|    |               |                                    |                                                                                                                                                                                            | 3 -- Two \                                              |
|    |               |                                    |                                                                                                                                                                                            | 4 -- Three or more                                      |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 23 | Socioeconomic | ST253Q01JA                         | How many \[digital devices\] with screens are there in your \[home\]?                                                                                                                      | 1 - 0\                                                  |
|    |               |                                    |                                                                                                                                                                                            | 2 - One\                                                |
|    |               |                                    |                                                                                                                                                                                            | 3 - Two\                                                |
|    |               |                                    |                                                                                                                                                                                            | 4 - Three\                                              |
|    |               |                                    |                                                                                                                                                                                            | 5 - Four\                                               |
|    |               |                                    |                                                                                                                                                                                            | 6 - Five\                                               |
|    |               |                                    |                                                                                                                                                                                            | 7 - 6 to 10\                                            |
|    |               |                                    |                                                                                                                                                                                            | 8 - More than 10                                        |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 24 | Socioeconomic | ST255Q01JA                         | How many books are there in your home?                                                                                                                                                     | 1 - There are no books.\                                |
|    |               |                                    |                                                                                                                                                                                            | 2 - 1-10 books\                                         |
|    |               |                                    |                                                                                                                                                                                            | 3 - 11-25 books\                                        |
|    |               |                                    |                                                                                                                                                                                            | 4 - 26-100 books\                                       |
|    |               |                                    |                                                                                                                                                                                            | 5 - 101-200 books\                                      |
|    |               |                                    |                                                                                                                                                                                            | 6 - 201-500 books\                                      |
|    |               |                                    |                                                                                                                                                                                            | 7 - More than 500 books                                 |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 25 | Wellbeing     | ST016Q01NA                         | Overall, how satisfied are you with your life as a whole these days?                                                                                                                       |                                                         |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 26 | Wellbeing     | ST263Q02JA                         | Your intelligence is something about you that you cannot change very much.                                                                                                                 | 1 -- Strongly Disagree\                                 |
|    |               |                                    |                                                                                                                                                                                            | 2 -- Disagree\                                          |
|    |               |                                    |                                                                                                                                                                                            | 3 -- Agree\                                             |
|    |               |                                    |                                                                                                                                                                                            | 4 -- Strongly Agree                                     |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 27 | Wellbeing     | ST295Q05JA                         | During a typical school week, on how many days do you do each of the following after leaving school? Exercise or practise a sport (e.g. running, cycling, aerobics, soccer, skating, )     | 1 - 0 days\                                             |
|    |               |                                    |                                                                                                                                                                                            | 2 - 1 day\                                              |
|    |               |                                    |                                                                                                                                                                                            | 3 - 2 days\                                             |
|    |               |                                    |                                                                                                                                                                                            | 4 - 3 days\                                             |
|    |               |                                    |                                                                                                                                                                                            | 5- 4 days\                                              |
|    |               |                                    |                                                                                                                                                                                            | 6- 5 or more days                                       |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 28 | Wellbeing     | ST301Q10JA                         | I like learning new things.                                                                                                                                                                | 1 -- SD\                                                |
|    |               |                                    |                                                                                                                                                                                            | 2 -- D\                                                 |
|    |               |                                    |                                                                                                                                                                                            | 3 -- Neither\                                           |
|    |               |                                    |                                                                                                                                                                                            | 4 -- A\                                                 |
|    |               |                                    |                                                                                                                                                                                            | 5 -- SA                                                 |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 29 | Wellbeing     | ST307Q10JA                         | I give up easily.                                                                                                                                                                          | 1 -- SD\                                                |
|    |               |                                    |                                                                                                                                                                                            | 2 -- D\                                                 |
|    |               |                                    |                                                                                                                                                                                            | 3 -- Neither\                                           |
|    |               |                                    |                                                                                                                                                                                            | 4 -- A\                                                 |
|    |               |                                    |                                                                                                                                                                                            | 5 -- SA                                                 |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 30 | Wellbeing     | ST309Q05JA                         | I carefully check homework before turning it in.                                                                                                                                           | 1 -- SD\                                                |
|    |               |                                    |                                                                                                                                                                                            | 2 -- D\                                                 |
|    |               |                                    |                                                                                                                                                                                            | 3 -- Neither\                                           |
|    |               |                                    |                                                                                                                                                                                            | 4 -- A\                                                 |
|    |               |                                    |                                                                                                                                                                                            | 5 -- SA                                                 |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 31 | Wellbeing     | ST322Q07JA                         | I feel nervous/anxious when I don\'t have my \<digital device\> near me.                                                                                                                   | 1 -- Never or almost never\                             |
|    |               |                                    |                                                                                                                                                                                            | 2 -- Less than half of the time\                        |
|    |               |                                    |                                                                                                                                                                                            | 3 -- About half of the time\                            |
|    |               |                                    |                                                                                                                                                                                            | 4 -- More than half of the time\                        |
|    |               |                                    |                                                                                                                                                                                            | 5 -- All or almost all of the time\                     |
|    |               |                                    |                                                                                                                                                                                            | 6 -- Not applicable                                     |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| 32 | Wellbeing     | ST345Q07JA                         | I feel nervous about approaching exams.                                                                                                                                                    | 1 -- SD\                                                |
|    |               |                                    |                                                                                                                                                                                            | 2 -- D\                                                 |
|    |               |                                    |                                                                                                                                                                                            | 3 -- Neither\                                           |
|    |               |                                    |                                                                                                                                                                                            | 4 -- A\                                                 |
|    |               |                                    |                                                                                                                                                                                            | 5 -- SA                                                 |
+----+---------------+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+

: {tbl-colwidths="\[10,10,10,40,30\]"}